#ifndef AUTOCALCMATH_TRIGONOMITRY_H
#define AUTOCALCMATH_TRIGONOMITRY_H 
#endif

#include "AutoCalcMath.Type.Definer.h"

AUTOCALCMATH_FLOAT AutoCalcMath_Sin(AUTOCALCMATH_FLOAT x);

AUTOCALCMATH_FLOAT AutoCalcMath_Cos(AUTOCALCMATH_FLOAT x);

AUTOCALCMATH_FLOAT AutoCalcMath_Tan(AUTOCALCMATH_FLOAT x);

