#ifndef AUTOCALCMATH_POWERS_H
#define AUTOCALCMATH_POWERS_H
#endif

#include "AutoCalc.Type.Definer.h"

AUTOCALCMATH_FLOAT SquareRoot(AUTOCALCMATH_FLOAT Subject);

AUTOCALCMATH_FLOAT Square(AUTOCALCMATH_FLOAT Subject);

AUTOCALCMATH_FLOAT CustomSquare(AUTOCALCMATH_FLOAT Subject, AUTOCALCMATH_INT Times);

AUTOCALCMATH_FLOAT CubeRoot(AUTOCALCMATH_FLOAT Subject);

AUTOCALCMATH_FLOAT Cube(AUTOCALCMATH_FLOAT Subject);

AUTOCALCMATH_FLOAT ToPowerOff(AUTOCALCMATH_FLOAT Subject, AUTOCALCMATH_FLOAT PowerOf);
